# creating mini project of student marks dataset analysis

In [35]:
import numpy as np

first we have to create a dummy student dataset for marks(100 students) data

In [36]:
dataset = np.random.randint(0, 101, size=(100, 5))
dataset

array([[ 25,  82,  43,  77,  70],
       [ 67,  40,  90,  18,  77],
       [ 42,   4,  12,  34,  13],
       [ 40,  77,  83,  83,  10],
       [ 22,  88,  49,  86,  60],
       [ 64,  69,  27,   5,   3],
       [ 74,  13,  32,  45,  16],
       [ 17,  52,   1,  37,  38],
       [ 72,  37,  33,  96,  97],
       [ 12,  95,  64,  59,  41],
       [ 29,  25,  21,  61,  48],
       [ 67,  68,  88,  10,  25],
       [ 64,  71,  30,  30,  11],
       [ 24,  35,  81,  18,  92],
       [ 18,  13,  93,  16,  30],
       [ 29,  22,  80,  38,  33],
       [  0,  24,   5,  59,  15],
       [ 22,  94,  73,  75,  29],
       [  4,  29,  52,   3,  35],
       [ 20,  86,  97,  50,  23],
       [ 56,  83,  17,  36,  64],
       [ 25,  71,  72,  51,   8],
       [100,  85,  56,  71,  10],
       [ 38,  13,  25,  70,  12],
       [ 68,  55,   4,  37,   5],
       [ 12,  63,  80,  22,   0],
       [ 44,   8,  25,  80,  45],
       [ 78,  85,  97,   3,  18],
       [ 81,  62,  73,  30,  18],
       [ 16,  

# Basic Analysis

now we have to get to know how many students in our dataset

In [37]:
students = dataset.shape[0]
students

100

In [117]:
subjects = np.array([100,100,100,100,100])
max_marks = subjects.sum().item()
max_marks

500

Total marks of each student

In [39]:
total_marks_each_student = dataset.sum(axis = 1)
total_marks_each_student

array([297, 292, 105, 293, 305, 168, 180, 145, 335, 271, 184, 258, 206,
       250, 170, 202, 103, 293, 123, 276, 256, 227, 322, 158, 169, 177,
       202, 281, 264, 266, 237, 303, 277, 304, 313, 150, 449, 332, 261,
       215, 300, 195, 247, 240, 163, 205, 245, 339, 214, 320, 289, 129,
       238, 174, 230, 344, 286, 247, 325, 240, 241, 251, 443, 233, 256,
       194, 267, 144, 165, 316, 251, 268, 217, 238, 318, 224, 255, 245,
       272, 173, 296, 294, 240, 228, 177, 301, 370, 298, 179, 255, 193,
       275, 197, 255, 366, 288, 323, 280, 197, 230])

Average marks of each student

In [51]:
avg_marks_students = np.mean(dataset, axis=1)
avg_marks_students

array([59.4, 58.4, 21. , 58.6, 61. , 33.6, 36. , 29. , 67. , 54.2, 36.8,
       51.6, 41.2, 50. , 34. , 40.4, 20.6, 58.6, 24.6, 55.2, 51.2, 45.4,
       64.4, 31.6, 33.8, 35.4, 40.4, 56.2, 52.8, 53.2, 47.4, 60.6, 55.4,
       60.8, 62.6, 30. , 89.8, 66.4, 52.2, 43. , 60. , 39. , 49.4, 48. ,
       32.6, 41. , 49. , 67.8, 42.8, 64. , 57.8, 25.8, 47.6, 34.8, 46. ,
       68.8, 57.2, 49.4, 65. , 48. , 48.2, 50.2, 88.6, 46.6, 51.2, 38.8,
       53.4, 28.8, 33. , 63.2, 50.2, 53.6, 43.4, 47.6, 63.6, 44.8, 51. ,
       49. , 54.4, 34.6, 59.2, 58.8, 48. , 45.6, 35.4, 60.2, 74. , 59.6,
       35.8, 51. , 38.6, 55. , 39.4, 51. , 73.2, 57.6, 64.6, 56. , 39.4,
       46. ])

now get Highest total marks of student

In [52]:
highest_marks = total_marks_each_student.max().item()
highest_marks

449

get the Lowest total marks

In [53]:
lowest_marks = total_marks_each_student.min().item()
lowest_marks

103

# Subject Analysis

get avg marks in each subject

In [54]:
avg_marks_subjects = np.mean(dataset, axis=0)
avg_marks_subjects

array([45.87, 56.79, 52.35, 47.76, 45.25])

get highest marks in each subjects

In [63]:
highest_marks_each_subjects = dataset.max(axis = 0)
highest_marks_each_subjects

array([100,  99,  99,  97, 100], dtype=int32)

get lowest marks in each subjects

In [64]:
lowest_marks_each_subjects = dataset.min(axis = 0)
lowest_marks_each_subjects

array([0, 0, 1, 2, 0], dtype=int32)

# step four pass/fail

In [84]:
pas = dataset[dataset >= 40]
pas

array([ 82,  43,  77,  70,  67,  40,  90,  77,  42,  40,  77,  83,  83,
        88,  49,  86,  60,  64,  69,  74,  45,  52,  72,  96,  97,  95,
        64,  59,  41,  61,  48,  67,  68,  88,  64,  71,  81,  92,  93,
        80,  59,  94,  73,  75,  52,  86,  97,  50,  56,  83,  64,  71,
        72,  51, 100,  85,  56,  71,  70,  68,  55,  63,  80,  44,  80,
        45,  78,  85,  97,  81,  62,  73,  92,  68,  90,  87,  45,  70,
        54,  79,  70,  96,  50,  98,  76,  48,  49,  54,  97,  66, 100,
        52,  54,  73,  72,  97,  79,  99,  87,  87,  46,  92,  85,  73,
        90,  47,  74,  77,  72,  79,  80,  99,  99,  56,  61,  60,  91,
        64,  93,  61,  52,  86,  50,  65,  69,  80,  52,  48,  84,  68,
        88,  73,  53,  95,  46,  73,  70,  90,  75,  90,  77,  72,  51,
        56,  79,  75,  55,  90,  48,  94,  90,  45,  83,  54,  81,  81,
        53,  99,  75,  72,  91,  47,  84,  83,  87,  74,  93,  77,  75,
        54,  91,  44,  63,  93,  78,  99,  84,  89,  61,  79,  5

In [85]:
total_pass = pas.size
total_pass

286

In [86]:
fail = dataset[ dataset < 40]
fail

array([25, 18,  4, 12, 34, 13, 10, 22, 27,  5,  3, 13, 32, 16, 17,  1, 37,
       38, 37, 33, 12, 29, 25, 21, 10, 25, 30, 30, 11, 24, 35, 18, 18, 13,
       16, 30, 29, 22, 38, 33,  0, 24,  5, 15, 22, 29,  4, 29,  3, 35, 20,
       23, 17, 36, 25,  8, 10, 38, 13, 25, 12,  4, 37,  5, 12, 22,  0,  8,
       25,  3, 18, 30, 18, 16,  0,  5, 30,  4,  5, 38, 34,  1, 37, 35,  5,
       36, 29, 21, 26, 13, 27, 11, 31,  6,  3, 31, 24, 11,  2, 20,  6, 17,
        2, 10, 11, 31, 34, 26, 18,  2, 12, 11, 39, 17,  3,  2,  5, 24,  7,
        0, 29, 16, 26,  4, 27, 32, 22, 15, 34, 37, 32, 17, 24,  7, 28, 16,
       37, 27, 32, 34, 12, 23, 22, 28, 22, 29, 35,  8, 36,  4, 17, 28, 27,
       31, 18, 35, 11, 13, 11, 34, 23, 14, 22, 15, 17,  3, 12, 10, 32, 38,
       10, 14,  3,  7,  7, 35, 30, 19, 34, 11, 24, 36, 39, 17, 14, 34, 24,
       28, 17, 39, 26,  7, 18, 27, 34, 32, 33, 31, 27, 18, 31, 17,  7, 24,
        6,  2, 33, 32, 19, 11,  2,  9, 16,  3], dtype=int32)

In [87]:
total_fail = fail.size
total_fail

214

# Top Students

In [101]:
top_students = avg_marks_students[avg_marks_students >= 80]
top_students

array([89.8, 88.6])

In [102]:
top_students_ids = np.where(avg_marks_students >= 80)[0]
top_students_ids

array([36, 62])

# Grade Distribution

In [118]:
persentage_of_students = (total_marks_each_student / max_marks) * 100
persentage_of_students

array([59.4, 58.4, 21. , 58.6, 61. , 33.6, 36. , 29. , 67. , 54.2, 36.8,
       51.6, 41.2, 50. , 34. , 40.4, 20.6, 58.6, 24.6, 55.2, 51.2, 45.4,
       64.4, 31.6, 33.8, 35.4, 40.4, 56.2, 52.8, 53.2, 47.4, 60.6, 55.4,
       60.8, 62.6, 30. , 89.8, 66.4, 52.2, 43. , 60. , 39. , 49.4, 48. ,
       32.6, 41. , 49. , 67.8, 42.8, 64. , 57.8, 25.8, 47.6, 34.8, 46. ,
       68.8, 57.2, 49.4, 65. , 48. , 48.2, 50.2, 88.6, 46.6, 51.2, 38.8,
       53.4, 28.8, 33. , 63.2, 50.2, 53.6, 43.4, 47.6, 63.6, 44.8, 51. ,
       49. , 54.4, 34.6, 59.2, 58.8, 48. , 45.6, 35.4, 60.2, 74. , 59.6,
       35.8, 51. , 38.6, 55. , 39.4, 51. , 73.2, 57.6, 64.6, 56. , 39.4,
       46. ])

In [131]:
grade_a_students = persentage_of_students[persentage_of_students >= 90]
print('Numbers of A Grade Students: ',grade_a_students.size)

Numbers of A Grade Students:  0


In [132]:
grade_b_students = persentage_of_students[(persentage_of_students >= 80) & (persentage_of_students <= 89)]
print('Numbers of B Grade Students: ',grade_b_students.size)

Numbers of B Grade Students:  1


In [134]:
grade_c_students = persentage_of_students[(persentage_of_students >= 70) & (persentage_of_students <= 79)]
print('Numbers of C Grade Students: ',grade_c_students.size)

Numbers of C Grade Students:  2


In [135]:
grade_d_students = persentage_of_students[(persentage_of_students >= 60) & (persentage_of_students <= 69)]
print('Numbers of D Grade Students: ',grade_d_students.size)

Numbers of D Grade Students:  16


In [138]:
grade_e_students = persentage_of_students[(persentage_of_students >= 50) & (persentage_of_students <= 59)]
print('Numbers of E Grade Students: ',grade_e_students.size)

Numbers of E Grade Students:  28


In [139]:
grade_f_students = persentage_of_students[(persentage_of_students <= 49)]
print('Numbers of F Grade Students: ',grade_f_students.size)

Numbers of F Grade Students:  47


# class statistics

overall class avg

In [141]:
overall_class_avg = dataset.mean().item()
overall_class_avg

49.604

class Highest scorer

In [142]:
class_highest_scorer = dataset.max().item()
class_highest_scorer

100

class Lowest scorer

In [143]:
class_lowest_scorer = dataset.min().item()
class_lowest_scorer

0

In [145]:
median_marks = np.median(dataset).item()
median_marks

49.0

standard deviation of class

In [149]:
std_deviation_of_class = np.std(dataset, ddof=1).item()
std_deviation_of_class

29.66545571072607

In [156]:
ranking = np.sort(total_marks_each_student)[::-1]
ranking

array([449, 443, 370, 366, 344, 339, 335, 332, 325, 323, 322, 320, 318,
       316, 313, 305, 304, 303, 301, 300, 298, 297, 296, 294, 293, 293,
       292, 289, 288, 286, 281, 280, 277, 276, 275, 272, 271, 268, 267,
       266, 264, 261, 258, 256, 256, 255, 255, 255, 251, 251, 250, 247,
       247, 245, 245, 241, 240, 240, 240, 238, 238, 237, 233, 230, 230,
       228, 227, 224, 217, 215, 214, 206, 205, 202, 202, 197, 197, 195,
       194, 193, 184, 180, 179, 177, 177, 174, 173, 170, 169, 168, 165,
       163, 158, 150, 145, 144, 129, 123, 105, 103])